#ifndef DYNRPG_BATTLE_ENCOUNTER_CONDITION_H
#define DYNRPG_BATTLE_ENCOUNTER_CONDITION_H

namespace RPG
{
//! Possible values for RPG::BattleData::encounterCondition
enum BattleEncounterCondition
{
	BENC_TYPE_NO_SPECIAL_CONDITIONS,
	BENC_TYPE_INITIATIVE,
	BENC_TYPE_BACK_ATTACK,
	BENC_TYPE_SURROUND_ATTACK,
	BENC_TYPE_PINCER_ATTACK,
};
}

#endif // DYNRPG_BATTLE_ENCOUNTER_CONDITION_H
